title = "SystemHandler"
gitRepoUrl = "https://github.com/Cetrei/SystemHandler"

gitSourceBranch = "Principal"
changelog = true

[docusaurus]
onBrokenLinks: 'ignore'
onBrokenMarkdownLinks = "warn"

organizationName = "Cetrei"
projectName = "SystemHandler"
url = "https://Cetrei.github.io"
baseUrl = "/SystemHandler"
tagline = "System Handler for roblox"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "Cross-Game Config"
description = "Whit this module you can share the settings of your systems in all your games so you don´t need to repeat the process."

[[home.features]]
title = "Safe execution"
description = "CGD System Handler uses Promises to handle your systems and prevent performance issues in your game."

[footer]
style = "dark"
copyright = "Copyright © 2021 Cetrei"
